version: '3.8'

services:

  postgres:
    restart: unless-stopped
    image: postgres:15.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - powersub
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  powersub:
    driver: bridge

volumes:
  postgres:
    driver: local