spring:
  application:
    name: powersub-core
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/powersub}
    username: ${DB_USER:powersub}
    password: ${DB_PASSWORD:powersub@123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog.xml
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      path: /api
server:
  port: 9010
springdoc:
  api-docs:
    path: /powersub-docs
